1.- Sacar una rebanada de pan bimbo (de preferencia que no sea una tapa).
2.- Partir uno de los cuadritos de la tableta de chocolate seleccionada.
3.- Posicionar ese cuadrito en una de las esquinas del pan de tal forma que no se salga del perímetro del pan.
4.- Doblar a la mitad el pan. (Se jala la esquina opuesta a la que esta el chocolate) 
5.- Con el vaso invertido \_/ ⬇️ usar la boca para definir el perimetro de la empanada y presionar fuertemente.
6.- Quitar el pan sobrante afuera del baso y disponer de el.
7.- Cerrar la empanadita con los dedos y ponerla al comal con fuego bajo.
8.- Dejar de 30-60 segundos y voltear.
9.- Repetir el paso 8 hasta que este dorada con un color cafe en el pan. 
10.- Servir en un plato y DISFRUTAR.